version: '3'
services:

  cms:
    build: .
    image: jlopezxs/keyuxt
    # env_file: .env
    environment:
      - MONGO_URI=mongodb://db/keyuxt
      - COOKIE_SECRET=chocolate-chips-haha-get-it
      - PORT=80
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:80

  db:
    image: mongo
