version: '3'
services:

  cms:
    build: .
    image: jlopezxs/keyuxt
    # env_file: .env
    environment:
      - MONGO_URI=mongodb://db/keyuxt
      - COOKIE_SECRET=chocolate-chips-haha-get-it
      - PORT=4000
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000

  db:
    image: mongo
